### ISSUE TITLE
share2 - pebble

### ISSUE THREAD

**Issue by bewest** [nightscout/cgm-pebble#46]
The new share2 version sometimes has battery information, and in some cases (such as with some of the bridge projects) the battery information is not needed.

If there's a simple way to hide/remove the battery info, perhaps through toggle in config, that would be awesome.  Thoughts/feedback welcome.  The other way for people to handle this is to delete the battery info from mongodb, so perhaps we can take care of this purely on the webapp side.  Feel free to close and toss the issue over there if that would be preferred.

P.S., :heart: sleep mode. Thanks, all.

**Comment by ELUTE** [comment]
We have discussed options for this. The easiest solution would be to delete device status collection or we could release a version without the rig %.

**Comment by bewest** [comment]
Hmmm, another solution might be to have the sidecar app delete all battery info when it starts.

**Comment by ELUTE** [comment]
That would be good too.

**Comment by sugabetic** [comment]
I had the last battery info from my rig showing up for days and decided to look at Mongo. I went to my Collections and then DeviceStatus collection and just clicked "Delete all". Fixed it. No "Rig%" showing up on my Pebble now. :dancer:

**Comment by bewest** [comment]
Closing this, thanks to everyone for documenting the discussion.  After toying around with this, I figured out an even simpler way: https://github.com/bewest/share2nightscout-bridge/issues/10
